# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'mongodb'

steps:

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

#- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
#  displayName: 'Push Image: '
#  inputs:
#    awsCredentials: 'awsviji'
#    regionName: 'us-east-1'
#    sourceImageName: 'mongodb'
#    repositoryName: 'mongodb'
#    pushTag: 'latest'
#    autoCreateRepository: true

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
#    artifactName: 'drop' 
#    publishLocation: 'Container' 
    # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

#- script: docker images
#  displayName: 'images list'

#- script: docker-compose up -d;
#  displayName: 'docker compose build'

#- bash: docker-compose -f docker-compose.yml up
#  displayName: 'docker compose build'

#- script: |
#    docker-compose -f docker-compose.yml --project-directory . -p docs up -d
#    docker wait docs_sut_1
#    docker-compose -f docker-compose.yml --project-directory . down